# Generated by Django 4.0.6 on 2022-07-09 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cou_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='课程名称')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('open_term', models.DateField(default=datetime.date, verbose_name='开设学期')),
            ],
            options={
                'verbose_name': '课程管理',
                'verbose_name_plural': '课程管理',
                'db_table': 'course',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生管理', 'verbose_name_plural': '学生管理'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_null',
        ),
        migrations.RemoveField(
            model_name='student',
            name='description',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='家庭住址'),
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.DateField(auto_now=True, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='计算机', max_length=40, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='student',
            name='enroll_time',
            field=models.DateField(auto_now=True, verbose_name='入学时间'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_ID',
            field=models.CharField(default='123456789', max_length=12, primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_password',
            field=models.CharField(default='000000', max_length=40, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', '男'), ('Female', '女')], default='Male', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='分数')),
                ('teacher', models.CharField(max_length=40, verbose_name='任课教师')),
                ('isretake', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='重修标记')),
                ('cou_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='课程名称')),
                ('stu_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='学生姓名')),
            ],
            options={
                'verbose_name': '成绩管理',
                'verbose_name_plural': '成绩管理',
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='图书ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='图书名称')),
                ('borrowDate', models.DateField(auto_now=True, verbose_name='借阅日期')),
                ('returnDate', models.DateField(auto_now=True, verbose_name='归还日期')),
                ('stu_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='读者ID')),
            ],
            options={
                'verbose_name': '图书管理',
                'verbose_name_plural': '图书管理',
                'db_table': '图书管理',
            },
        ),
    ]
